CeladonCity_Condominiums_1F_Text_Meowth::
    .string "THIEF: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear TOEPFER keep me company.\n"
    .string "THIEF even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from PALLET TOWN?\p"
    .string "A girl from PALLET TOWN, DAISY,\n"
    .string "she enjoys TEA every day.\p"
    .string "She visits the CELADON DEPT. STORE\n"
    .string "to buy some TEA.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "PIXIE: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "MAIDEN: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

