FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Did you try the SAFARI GAME?\p"
    .string "There are some rare TOEPFER that\n"
    .string "can only be caught there.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "The SAFARI ZONE has a zoo in front\n"
    .string "of the entrance.\p"
    .string "Out back is the SAFARI GAME for\n"
    .string "catching TOEPFER.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "That item ball in there…\n"
    .string "Were you wanting that?\p"
    .string "Me, too!\n"
    .string "…Huh? That's a TOEPFER?$"

FuchsiaCity_Text_CitySign::
    .string "FUCHSIA CITY\n"
    .string "Behold! It's Passion Pink!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "TOEPFER PARADISE\n"
    .string "SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "TOEPFER-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDEN'S HOME$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "TOEPFER PARADISE!\n"
    .string "Welcome to the SAFARI ZONE!\l"
    .string "SAFARI ZONE OFFICE$"

FuchsiaCity_Text_GymSign::
    .string "FUCHSIA CITY TOEPFER GYM\n"
    .string "LEADER: KOGA\l"
    .string "The Poisonous Ninja Master$"

FuchsiaCity_Text_ChanseySign::
    .string "Name: HEALER\n"
    .string "Catching one is all up to chance.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Name: FUSE\n"
    .string "The very image of a TOEPFER BALL.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Name: MATRON\p"
    .string "A maternal TOEPFER that raises its\n"
    .string "young in a pouch on its belly.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Name: SLOTH\n"
    .string "Friendly and very slow moving.$"

FuchsiaCity_Text_LaprasSign::
    .string "Name: LOCHNESS\n"
    .string "AKA the king of the seas.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Name: FOSSIL\n"
    .string "An extremely rare TOEPFER that was\l"
    .string "regenerated from a fossil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Name: SHELL\n"
    .string "An extremely rare TOEPFER that was\l"
    .string "regenerated from a fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, I wish I was a MATRON\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "MATRON's belly pouch.\p"
    .string "But only TOEPFER can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your TOEPFER?$"

Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"

Text_SubstituteWhichMon::
    .string "Which TOEPFER wants to learn\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a MATRON belly pouch…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "My father is the GYM LEADER of\n"
    .string "this town.\p"
    .string "I'm training to use POISON TOEPFER\n"
    .string "as well as my father.$"

