VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my MAILROOM to fly a\n"
    .string "letter to SAFFRON in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "MAILROOM: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI,\n"
    .string "I hope to see you soon.\p"
    .string "I heard SAFFRON has problems with\n"
    .string "TEAM ROCKET.\p"
    .string "VERMILION appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my MAILROOM to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

