SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "You can keep any item you find in\n"
    .string "the SAFARI ZONE.\p"
    .string "But, you'll run out of time if you\n"
    .string "try for all of them at once.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Go to the deepest part of the\n"
    .string "SAFARI ZONE. You will win a prize!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "My NEWBIE evolved into HOTSHOT.\p"
    .string "But, a friend's NEWBIE turned into a\n"
    .string "SALESREP. I wonder why?$"

