VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "There are wicked people who will\n"
    .string "use TOEPFER for criminal acts.\p"
    .string "TEAM ROCKET traffics in rare\n"
    .string "TOEPFER, for example.\p"
    .string "They also abandon TOEPFER that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I think TOEPFER can be good or\n"
    .string "bad. It depends on the TRAINER.$"

