CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "TOEPFER stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP UP increases the base HP of a\n"
    .string "TOEPFER.\p"
    .string "CALCIUM raises the base SP. ATK\n"
    .string "stat of one TOEPFER.\p"
    .string "ZINC boosts the base SP. DEF stat\n"
    .string "of one TOEPFER.\p"
    .string "CARBOS enhances the base SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for TOEPFER stat\n"
    .string "enhancers.\p"
    .string "PROTEIN increases the base ATTACK\n"
    .string "power.\p"
    .string "IRON increases the base DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUGSTORE$"

