LavenderTown_House1_Text_Cubone::
    .string "ORPHAN: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "Those horrible ROCKETS!\n"
    .string "They deserve no mercy!\p"
    .string "That poor ORPHAN's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of TOEPFER TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

