ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a TOEPFER CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing TOEPFER.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "TOEPFER CENTERS heal your tired,\n"
    .string "hurt, or fainted TOEPFER.\p"
    .string "They make all TOEPFER completely\n"
    .string "healthy.$"

