PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What!?\p"
    .string "TEAM ROCKET is at MT. MOON?\n"
    .string "Huh?\p"
    .string "I'm on the phone!\n"
    .string "Scram!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "EMCEE: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn!\p"
    .string "When EMCEE sings, TOEPFER get\n"
    .string "drowsy…\p"
    .string "…Me, too…\n"
    .string "Snore…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I really want a TECHIE, so I'm\n"
    .string "trading my PIXIE for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "I'm trading TOEPFER with that kid\n"
    .string "there.\p"
    .string "I had two TECHIE, so I figured\n"
    .string "I might as well trade one.$"

