FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "We nicknamed the WARDEN\n"
    .string "“SLOTH.”\p"
    .string "You know, he has that vacant look\n"
    .string "like a SLOTH.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "WARDEN SLOTH is very\n"
    .string "knowledgeable about TOEPFER.\p"
    .string "He even has some fossils of rare,\n"
    .string "extinct TOEPFER.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "WARDEN SLOTH came in, but\n"
    .string "I couldn't understand him.\p"
    .string "I think he's got a speech problem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "WARDEN SLOTH is running a\n"
    .string "promotion campaign right now.\p"
    .string "Try to get to the farthest corner\n"
    .string "of the SAFARI ZONE.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"

