PewterCity_House1_Text_Nidoran::
    .string "NEWHIRE: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NEWHIRE, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Our TOEPFER's an outsider, so it's\n"
    .string "finicky and hard to handle.\p"
    .string "An outsider is a TOEPFER that you\n"
    .string "get in a trade.\p"
    .string "It grows fast, but it may ignore an\n"
    .string "unskilled TRAINER in battle.\p"
    .string "If only we had some BADGES…$"

